version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./sql/init.sql:/data/application/init.sql
    # networks:
    #   - mynetwork

# networks:
#   mynetwork:
#     name: mynetwork

volumes:
  db-data:


