version: '3.1'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf
    ports:
      - 3306:3306

networks:
  sf:
    driver: bridge